Prevent FileNotFoundError by copying to installation dir the json files
The json file was not installed upon pip install.
The fact that if pip install -e is used a symbolic link is created has previously hidden this issue.

FileNotFoundError: [Errno 2] No such file or directory: '[omissis...]\\site-packages\\pvtrace\\cli\\pvtrace-schema-scene-spec.json'